package com.auction.dto;

import java.math.BigDecimal;

public class BidDto {
    private String bidId;
    private String bidderId;
    private String bidderName;
    private String itemName;
    private BigDecimal amount;
    private String timestamp;
    private boolean autoGenerated;

    public BidDto() {
    }

    public BidDto(String bidId, String bidderId, String bidderName, String itemName, BigDecimal amount,
                  String timestamp, boolean autoGenerated) {
        this.bidId = bidId;
        this.bidderId = bidderId;
        this.bidderName = bidderName;
        this.itemName = itemName;
        this.amount = amount;
        this.timestamp = timestamp;
        this.autoGenerated = autoGenerated;
    }

    public String getBidId() {
        return bidId;
    }

    public void setBidId(String bidId) {
        this.bidId = bidId;
    }

    public String getBidderId() {
        return bidderId;
    }

    public void setBidderId(String bidderId) {
        this.bidderId = bidderId;
    }

    public String getBidderName() {
        return bidderName;
    }

    public void setBidderName(String bidderName) {
        this.bidderName = bidderName;
    }

    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    public String getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }
}
