package com.auction.common;

public enum RequestType {
    PING,
    MESSAGE,

    LOGIN,
    REGISTER,

    GET_AUCTIONS,
    GET_AUCTION_DETAIL,
    CREATE_AUCTION,
    UPDATE_AUCTION,
    DELETE_AUCTION,
    APPROVE_AUCTION,
    REJECT_AUCTION,
    FINISH_AUCTION,

    PLACE_BID,
    REGISTER_AUTO_BID,
    DEPOSIT_MONEY,
    GET_BALANCE,
    GET_PENDING_DEPOSIT_REQUESTS,
    APPROVE_DEPOSIT,
    REJECT_DEPOSIT,

    GET_UNREAD_NOTIFICATIONS,
    MARK_NOTIFICATION_READ,

    SUBSCRIBE_AUCTION,

    EXIT
}
