package com.auction.model;

import com.auction.util.MoneyUtil;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class BidTransaction extends Entity {
    private static final long serialVersionUID = 1L;

    private String auctionId;
    private String bidderId;
    private String bidderName;
    private String itemName;
    private BigDecimal amount;
    private LocalDateTime timestamp;
    private boolean autoGenerated;

    // Trường tương thích với màn hình TransactionHistory cũ
    private int numericId;

    public BidTransaction() {
        super();
        this.amount = BigDecimal.ZERO;
        this.timestamp = LocalDateTime.now();
        this.bidderName = "Không rõ";
        this.itemName = "Không rõ";
    }

    public BidTransaction(String auctionId, String bidderId, BigDecimal amount,
                          LocalDateTime timestamp, boolean autoGenerated) {
        this(auctionId, bidderId, bidderId, auctionId, amount, timestamp, autoGenerated);
    }

    public BidTransaction(String auctionId, String bidderId, String bidderName, String itemName,
                          BigDecimal amount, LocalDateTime timestamp, boolean autoGenerated) {
        super();
        this.auctionId = auctionId;
        this.bidderId = bidderId;
        this.bidderName = bidderName;
        this.itemName = itemName;
        this.amount = MoneyUtil.normalize(amount);
        this.timestamp = timestamp == null ? LocalDateTime.now() : timestamp;
        this.autoGenerated = autoGenerated;
        this.numericId = (int) (System.currentTimeMillis() % Integer.MAX_VALUE);
    }

    public BidTransaction(int numericId, Bidder bidder, Item item, double amount, LocalDateTime timestamp) {
        super();
        this.numericId = numericId;
        this.auctionId = item == null ? "" : item.getId();
        this.bidderId = bidder == null ? "" : bidder.getId();
        this.bidderName = bidder == null ? "Không rõ" : bidder.getName();
        this.itemName = item == null ? "Không rõ" : item.getName();
        this.amount = MoneyUtil.fromDouble(amount);
        this.timestamp = timestamp == null ? LocalDateTime.now() : timestamp;
        this.autoGenerated = false;
    }

    public String getAuctionId() {
        return auctionId;
    }

    public String getBidderId() {
        return bidderId;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public int getNumericId() {
        return numericId;
    }

    public String getBidderName() {
        return bidderName == null || bidderName.isBlank() ? bidderId : bidderName;
    }

    public String getItemName() {
        return itemName == null || itemName.isBlank() ? auctionId : itemName;
    }

    public BigDecimal getBidAmountValue() {
        return amount == null ? BigDecimal.ZERO : MoneyUtil.normalize(amount);
    }

    public double getBidAmount() {
        return amount == null ? 0.0 : amount.doubleValue();
    }

    public String getFormattedTime() {
        LocalDateTime safeTime = timestamp == null ? LocalDateTime.now() : timestamp;
        return safeTime.format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));
    }
}
