package com.auction.model;

import java.math.BigDecimal;
import java.time.LocalDateTime;

public class BidTransaction extends Entity {
    private static final long serialVersionUID = 1L;

    private String auctionId;
    private String bidderId;
    private BigDecimal amount;
    private LocalDateTime timestamp;
    private boolean autoGenerated;

    public BidTransaction() {
        super();
    }

    public BidTransaction(String auctionId, String bidderId, BigDecimal amount,
            LocalDateTime timestamp, boolean autoGenerated) {
        super();
        this.auctionId = auctionId;
        this.bidderId = bidderId;
        this.amount = amount;
        this.timestamp = timestamp;
        this.autoGenerated = autoGenerated;
    }

    public String getAuctionId() {
        return auctionId;
    }

    public String getBidderId() {
        return bidderId;
    }

    public BigDecimal getAmount() {
        return amount;
    }

    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }
}
